name: Testing
on: push

jobs: 
  test_project:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    with: 
      python-version: '3'
    - name: Run Django Unit Test
      run: |
      pip3 install --user django
      python3 manage.py test
